"""Durable workflow store interface (batch workflow — replaces in-memory registry)."""
from __future__ import annotations
from typing import Protocol, runtime_checkable

@runtime_checkable
class WorkflowStore(Protocol):
    async def create_workflow(self, tenant_id: str, name: str, definition: dict, created_by: str | None = None) -> dict: ...
    async def get_workflow(self, tenant_id: str, workflow_id: str) -> dict | None: ...
    async def update_workflow(self, tenant_id: str, workflow_id: str, updates: dict) -> dict: ...
    async def create_version(self, workflow_id: str, graph_config: dict) -> dict: ...
    async def get_version(self, version_id: str) -> dict | None: ...
    async def create_execution(self, workflow_id: str, version_id: str, tenant_id: str, input_payload: dict) -> dict: ...
    async def get_execution(self, execution_id: str) -> dict | None: ...
    async def update_execution_state(self, execution_id: str, status: str, current_node_id: str | None = None, checkpoint: dict | None = None) -> dict: ...
    async def recover_executions(self, tenant_id: str) -> list[dict]: ...
    async def list_executions(self, tenant_id: str, status: str | None = None) -> list[dict]: ...
