import React from 'react'
import { createRoot } from 'react-dom/client'
import App from './app/app'
import './styles/globals.css'
import './styles/components.css'
import './styles/effects.css'
import './styles/app.css'
import './styles/voice-agents.css'
import './styles/use-cases.css'
import './styles/customer-service.css'
import './styles/answering-service.css'
import './styles/appointment-setter.css'
import './styles/telemarketing.css'
import './styles/industries.css'
import './styles/integrations.css'
import './styles/pricing.css'
import './styles/developers.css'
import './styles/solutions.css'
import './styles/security.css'
import './styles/compliance.css'
import './styles/resources.css'
import './styles/blog.css'
import './styles/company.css'
import './styles/legal.css'
import './styles/auth.css'
import './styles/contact.css'
import './styles/docs.css'
import './styles/trust.css'

createRoot(document.getElementById('root')).render(<App />)
