"""Measure source, live route registration, and pytest collection; never guess counts."""
from __future__ import annotations
import argparse
from contextlib import redirect_stdout
import io
import json
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


def measure():
    source = []
    for directory in ('app', 'services', 'dashboard/src', 'dashboard-next', 'sdk'):
        for path in (ROOT / directory).rglob('*'):
            if path.is_file() and path.suffix in {'.py', '.ts', '.tsx', '.js', '.rs', '.go', '.cpp', '.h', '.hpp'} and not set(path.parts).intersection({'node_modules', 'target', 'build', 'dist', 'vendor', '__pycache__', '.next'}):
                source.append(path)
    collected = subprocess.run([sys.executable, '-m', 'pytest', '--collect-only', '-q'], cwd=ROOT, text=True, capture_output=True)
    if collected.returncode:
        raise RuntimeError('Test collection failed; no counts published.\n' + collected.stdout + collected.stderr)
    nodes = [line for line in collected.stdout.splitlines() if line.startswith('tests/') and '::' in line]
    if not nodes or len(nodes) != len(set(nodes)):
        raise RuntimeError('No unique test population available')
    with redirect_stdout(io.StringIO()):
        from app.main import app
    return {'source_files': len(source), 'source_physical_lines': sum(len(p.read_text().splitlines()) for p in source), 'registered_routes': len(app.routes), 'collected_pytest_nodes': len(nodes), 'passed_tests': 'not measured by collection'}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write-readme', action='store_true')
    args = parser.parse_args()
    stats = measure()
    payload = json.dumps(stats, indent=2)
    print(payload)
    if args.write_readme:
        (ROOT / 'README.md').write_text('# VoxDesk\n\nDevelopment repository; not certified production-ready.\n\n## Status per feature\n\nThe only current sales capability table is [the generated verified matrix](docs/SALES/FEATURE_MATRIX_VERIFIED.md). API presence and source volume are not proof of live operation. No live capabilities are claimed here without qualifying evidence.\n\n## Measured repository statistics\n\nGenerated by `python scripts/repo_stats.py --write-readme`. Physical source lines exclude generated/vendor/build trees; collected tests are not passed tests.\n\n```json\n' + payload + '\n```\n\n## Development setup\n\nUse Python 3.12 and the pinned requirements. Copy `.env.example` to `.env` and supply deployment-specific secrets before starting services.\n\n```sh\npython -m venv .venv\n. .venv/bin/activate\npip install -r requirements-validation.txt\nmake up\nmake migrate\npython -m scripts.create_owner --help\n```\n\nRun `make verify-truth`, `make contracts-check`, and the application test suite before release. External-provider credentials must be supplied separately; local contracts do not establish real delivery.\n\nHistorical reports are audit records, not current capability promises. See `reports/PART_0_REPORT.md` for this pass and residual gates.\n\n## Commit policy\n\nUse the requested task ID in each scoped commit (for example, `P0-08: remove verified generated UI tails`). Do not combine unrelated staged work, generated padding, secrets or downloaded dependencies. Truth guards run in CI; never expand a shrink-only exception to hide a regression.\n')


if __name__ == '__main__':
    main()
