"""
Generic signed webhook.

The provider for everyone who is not on GoHighLevel, HubSpot or Jobber: Zapier,
Make, n8n, or a bespoke endpoint. It is also the honest version of what the
old `crm.py` actually was — the difference is that this one signs, times, keys
and validates.

**The signature scheme**, which a receiver must implement:

    signed = f"{timestamp}.{raw_body}"
    signature = hmac_sha256(tenant_signing_secret, signed).hexdigest()

sent as::

    X-VoxDesk-Signature: sha256=<hex>
    X-VoxDesk-Timestamp: <unix seconds>
    X-VoxDesk-Event: lead.created
    X-VoxDesk-Idempotency-Key: <stable key>
    X-VoxDesk-Delivery: <uuid, unique per attempt>

Three details that are the difference between a signature and a decoration:

* **The timestamp is inside the signed string.** Signing only the body lets an
  attacker replay a captured request forever; the receiver cannot tell an old
  valid request from a new one. With the timestamp signed, a receiver rejects
  anything outside a few minutes and replay stops working.
* **The secret is per tenant**, generated by us, never shared between
  tenants, and never sent in a payload. A shared platform secret would let any
  customer forge any other customer's events.
* **Idempotency-Key is stable across retries; Delivery is not.** A receiver
  deduplicates on the first and logs the second. Making one value do both jobs
  means a retry either looks like a new event or is impossible to trace.
"""
from __future__ import annotations

import hashlib
import hmac
import json
import secrets
import time
import uuid
from typing import Any
from urllib.parse import urlparse

from app.integrations.crm.base import Capability, CrmProvider
from app.integrations.crm.errors import (
    CrmConfigurationError,
    CrmValidationError,
)
from app.integrations.crm.models import CrmResult, HealthResult

SIGNATURE_HEADER = "X-VoxDesk-Signature"
TIMESTAMP_HEADER = "X-VoxDesk-Timestamp"
EVENT_HEADER = "X-VoxDesk-Event"
IDEMPOTENCY_HEADER = "X-VoxDesk-Idempotency-Key"
DELIVERY_HEADER = "X-VoxDesk-Delivery"

#: How much clock skew a receiver should tolerate. Documented here because it
#: is part of the contract we publish, not just our own setting.
RECOMMENDED_TOLERANCE_SECONDS = 300


def generate_signing_secret() -> str:
    """A fresh per-tenant webhook secret."""
    return secrets.token_hex(32)


def sign(secret: str, *, timestamp: int, body: str) -> str:
    """
    The signature a receiver must recompute.

    Exported so the documentation, the tests and any receiver library all use
    one implementation rather than three subtly different ones.
    """
    signed = f"{timestamp}.{body}".encode()
    digest = hmac.new(secret.encode(), signed, hashlib.sha256).hexdigest()
    return f"sha256={digest}"


def verify(secret: str, *, timestamp: int, body: str, signature: str,
           tolerance_seconds: int = RECOMMENDED_TOLERANCE_SECONDS,
           now: float | None = None) -> bool:
    """
    Reference verification, used by our own inbound handler and by the tests.

    `hmac.compare_digest`, not `==`: comparing signatures with a short-circuit
    equality leaks their prefix through timing.
    """
    current = time.time() if now is None else now
    if abs(current - timestamp) > tolerance_seconds:
        return False
    return hmac.compare_digest(sign(secret, timestamp=timestamp, body=body), signature)


class WebhookProvider(CrmProvider):
    name = "webhook"
    capabilities = frozenset({
        Capability.UPSERT_CONTACT,
        Capability.CREATE_CONTACT,
        Capability.CREATE_NOTE,
        Capability.CREATE_ACTIVITY,
        Capability.CREATE_APPOINTMENT,
        Capability.CANCEL_APPOINTMENT,
        Capability.ADD_TAG,
        Capability.ADD_CUSTOM_FIELDS,
        Capability.HEALTH_CHECK,
    })
    # GET_CONTACT is absent: a fire-and-forget webhook has nothing to read
    # back. Declaring it and returning None would make "not found" and "cannot
    # look up" indistinguishable to the service layer.

    # ------------------------------------------------------------- config ---

    @property
    def _url(self) -> str:
        url = (self.context.config or {}).get("url") or ""
        if not url:
            raise CrmConfigurationError(
                "webhook url is not configured", provider=self.name
            )
        parsed = urlparse(url)
        if parsed.scheme != "https":
            # Requirement 10 says HTTPS, and it matters: the payload contains
            # customer phone numbers and call summaries. The check is here as
            # well as at the API boundary because config can also be written
            # by a migration or a fixture.
            raise CrmConfigurationError(
                "webhook url must use https", provider=self.name
            )
        if not parsed.netloc:
            raise CrmConfigurationError("webhook url is malformed", provider=self.name)
        return url

    @property
    def _secret(self) -> str:
        secret = (self.context.credentials or {}).get("signing_secret") or ""
        if not secret:
            raise CrmConfigurationError(
                "webhook signing secret is not configured; unsigned delivery is "
                "not supported",
                provider=self.name,
            )
        return secret

    # ------------------------------------------------------------ delivery ---

    def build_envelope(
        self, event_type: str, payload: dict[str, Any], *, idempotency_key: str
    ) -> dict[str, Any]:
        """
        The body shape. Stable, versioned, and free of anything secret.

        Note what is *not* here: no signing secret, no provider credentials,
        no VoxDesk internal ids beyond the tenant-scoped entity id. The
        signing secret is the receiver's copy of a shared secret — echoing it
        in the payload it authenticates would be self-defeating.
        """
        return {
            "specversion": "1.0",
            "source": "voxdesk",
            "type": event_type,
            "id": idempotency_key,
            "time": _iso_now(),
            "data": payload,
        }

    async def deliver(
        self, event_type: str, payload: dict[str, Any], *, idempotency_key: str
    ) -> CrmResult:
        envelope = self.build_envelope(
            event_type, payload, idempotency_key=idempotency_key
        )
        # Serialize once and sign exactly the bytes that are sent. Signing a
        # re-serialized copy is how signatures start failing for unicode
        # payloads only.
        body = json.dumps(envelope, separators=(",", ":"), sort_keys=True, default=str)
        timestamp = int(time.time())
        delivery_id = str(uuid.uuid4())

        headers = {
            SIGNATURE_HEADER: sign(self._secret, timestamp=timestamp, body=body),
            TIMESTAMP_HEADER: str(timestamp),
            EVENT_HEADER: event_type,
            IDEMPOTENCY_HEADER: idempotency_key,
            DELIVERY_HEADER: delivery_id,
        }

        status, response = await self.request(
            "POST", self._url, json_body=envelope, headers=headers,
            expected=(200, 201, 202, 204),
        )
        self._validate_response(status, response)
        return CrmResult(
            external_id=_external_id(response) or idempotency_key,
            details={"status": status, "delivery_id": delivery_id},
        )

    def _validate_response(self, status: int, response: Any) -> None:
        """
        Requirement 10 asks for response validation.

        A 2xx is the acknowledgement. Beyond that we only look for an explicit
        rejection: a receiver that answers 200 with `{"ok": false}` is saying
        it did not accept the event, and treating that as success is precisely
        the "claimed synced when it was not" failure the brief forbids.
        """
        if isinstance(response, dict) and response.get("ok") is False:
            raise CrmValidationError(
                f"the webhook receiver returned HTTP {status} but reported "
                f"ok=false",
                provider=self.name, status=status,
            )

    # ---------------------------------------------------------- operations ---
    #
    # Every operation is the same POST with a different event type. They exist
    # as separate methods so the service layer treats this provider exactly
    # like the others rather than special-casing it.

    async def upsert_contact(self, contact) -> CrmResult:
        return await self.deliver(
            "contact.upserted", _contact_payload(contact),
            idempotency_key=_fallback_key(contact),
        )

    async def create_contact(self, contact) -> CrmResult:
        return await self.deliver(
            "contact.created", _contact_payload(contact),
            idempotency_key=_fallback_key(contact),
        )

    async def create_note(self, external_contact_id: str, activity) -> CrmResult:
        return await self.deliver(
            "note.created",
            {
                "contact_id": external_contact_id,
                "title": activity.title,
                "body": activity.body,
            },
            idempotency_key=f"note:{external_contact_id}:{activity.title}",
        )

    async def create_activity(self, external_contact_id: str, activity) -> CrmResult:
        return await self.create_note(external_contact_id, activity)

    async def create_appointment(
        self, appointment, *, external_contact_id: str | None = None
    ) -> CrmResult:
        return await self.deliver(
            "appointment.booked",
            {
                "title": appointment.title,
                "starts_at": appointment.starts_at.isoformat(),
                "ends_at": appointment.ends_at.isoformat(),
                "contact": _contact_payload(appointment.contact),
            },
            idempotency_key=f"appt:{appointment.starts_at.isoformat()}",
        )

    async def cancel_appointment(self, external_event_id: str) -> CrmResult:
        return await self.deliver(
            "appointment.cancelled", {"appointment_id": external_event_id},
            idempotency_key=f"appt-cancel:{external_event_id}",
        )

    async def add_tag(self, external_contact_id: str, tags: list[str]) -> CrmResult:
        return await self.deliver(
            "contact.tagged", {"contact_id": external_contact_id, "tags": tags},
            idempotency_key=f"tag:{external_contact_id}:{','.join(sorted(tags))}",
        )

    async def add_custom_fields(
        self, external_contact_id: str, fields: dict[str, Any]
    ) -> CrmResult:
        return await self.deliver(
            "contact.fields_updated",
            {"contact_id": external_contact_id, "fields": fields},
            idempotency_key=f"fields:{external_contact_id}",
        )

    async def health_check(self) -> HealthResult:
        async def probe():
            await self.deliver(
                "voxdesk.ping",
                {"message": "VoxDesk connection test"},
                idempotency_key=f"ping:{uuid.uuid4()}",
            )

        return await self._timed_health_check(probe)


# ------------------------------------------------------------------ helpers ---

def _iso_now() -> str:
    from datetime import datetime, timezone
    return datetime.now(timezone.utc).isoformat()


def _contact_payload(contact) -> dict[str, Any]:
    return {
        "first_name": contact.first_name,
        "last_name": contact.last_name,
        "phone": contact.phone,
        "email": contact.email,
        "company": contact.company,
        "source": contact.source,
        "tags": list(contact.tags),
        "intent": contact.intent,
        "lead_score": contact.lead_score,
        "custom_fields": dict(contact.custom_fields or {}),
    }


def _fallback_key(contact) -> str:
    """
    Used only when an operation is called directly rather than through the
    service layer, which always supplies the real event key.
    """
    return f"contact:{contact.phone or contact.email or uuid.uuid4()}"


def _external_id(response: Any) -> str | None:
    if isinstance(response, dict):
        for key in ("id", "contact_id", "external_id"):
            if response.get(key):
                return str(response[key])
    return None