import React, { useRef } from 'react';
import type { VoiceState } from '../../types/voice';
export interface VoiceOrbProps { state:VoiceState; size?:'sm'|'md'|'lg'; className?:string; }
export function VoiceOrb({state,size='md',className=''}:VoiceOrbProps){
  const orbRef=useRef<HTMLDivElement>(null);
  const sizes={sm:'h-16 w-16',md:'h-24 w-24',lg:'h-32 w-32'};
  const stateConfig:Record<VoiceState,{color:string; animation:string; label:string}>={IDLE:{color:'from-blue-500/20 to-violet-500/20',animation:'animate-pulse',label:'Idle'},LISTENING:{color:'from-emerald-500/30 to-cyan-500/30',animation:'animate-ping',label:'Listening'},PROCESSING:{color:'from-amber-500/30 to-orange-500/30',animation:'animate-spin',label:'Processing'},SPEAKING:{color:'from-blue-500/40 to-violet-500/40',animation:'animate-pulse',label:'Speaking'},INTERRUPTED:{color:'from-red-500/20 to-orange-500/20',animation:'animate-bounce',label:'Interrupted'},ERROR:{color:'from-red-500/30 to-red-700/30',animation:'',label:'Error'},NOT_CONFIGURED:{color:'from-gray-500/20 to-gray-700/20',animation:'',label:'Not Configured'}};
  const config=stateConfig[state];
  return (<div className={`relative flex items-center justify-center ${className}`} role="img" aria-label={`Voice state: ${config.label}`}><div className={`absolute ${sizes[size]} rounded-full bg-gradient-to-br ${config.color} blur-xl ${config.animation}`} aria-hidden="true" /><div className={`absolute ${sizes[size]} rounded-full border border-white/10 bg-gradient-to-br ${config.color} backdrop-blur`} aria-hidden="true"><div className="absolute inset-0 rounded-full bg-gradient-to-b from-white/20 to-transparent" /></div><div ref={orbRef} className={`relative ${size==='sm'?'h-10 w-10':size==='md'?'h-16 w-16':'h-20 w-20'} rounded-full bg-gradient-to-br from-blue-500 to-violet-600 shadow-lg shadow-blue-500/20 ${state==='LISTENING'?'animate-pulse':''} ${state==='SPEAKING'?'animate-[pulse_1s_ease-in-out_infinite]':''}`}><div className="absolute left-1 top-1 h-1/3 w-1/3 rounded-full bg-white/30 blur-sm" aria-hidden="true" />{state==='LISTENING'&&(<div className="absolute inset-0 flex items-center justify-center"><div className="h-2 w-2 rounded-full bg-emerald-400 animate-ping" /></div>)}{state==='ERROR'&&(<div className="absolute inset-0 flex items-center justify-center text-white font-bold">!</div>)}</div><span className="sr-only">{config.label}</span></div>);
}
